info:
  artifactId: "${project.name}"
  version: "${project.version}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_security?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none